services:
  - type: web
    name: dark-thila-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: BASE_PATH
        value: /
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
